{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7ec1dbe4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "The system cannot find the path specified.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting chainer==2.1.0\n",
      "  Using cached chainer-2.1.0.tar.gz (324 kB)\n",
      "Requirement already satisfied: filelock in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer==2.1.0) (3.3.1)\n",
      "Requirement already satisfied: mock in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer==2.1.0) (4.0.3)\n",
      "Requirement already satisfied: nose in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer==2.1.0) (1.3.7)\n",
      "Requirement already satisfied: numpy>=1.9.0 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer==2.1.0) (1.20.3)\n",
      "Requirement already satisfied: protobuf>=2.6.0 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer==2.1.0) (3.19.6)\n",
      "Requirement already satisfied: six>=1.9.0 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer==2.1.0) (1.16.0)\n",
      "Collecting cupy<1.1\n",
      "  Using cached cupy-1.0.3.tar.gz (1.3 MB)\n",
      "  Using cached cupy-1.0.2.tar.gz (1.4 MB)\n",
      "  Using cached cupy-1.0.1.tar.gz (1.3 MB)\n",
      "  Using cached cupy-1.0.0.1.tar.gz (1.3 MB)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\sinnd\\anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\sinnd\\\\AppData\\\\Local\\\\Temp\\\\pip-install-vqangms_\\\\cupy_00deaeca448d425da4d39ec650e4212a\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\sinnd\\\\AppData\\\\Local\\\\Temp\\\\pip-install-vqangms_\\\\cupy_00deaeca448d425da4d39ec650e4212a\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-pip-egg-info-qd8r55r6'\n",
      "         cwd: C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_00deaeca448d425da4d39ec650e4212a\\\n",
      "    Complete output (27 lines):\n",
      "    C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_00deaeca448d425da4d39ec650e4212a\\install\\build.py:38: SyntaxWarning: \"is not\" with a literal. Did you mean \"!=\"?\n",
      "      if _cuda_path is not 'NOT_INITIALIZED':\n",
      "    a.cpp\n",
      "    C:\\Users\\sinnd\\AppData\\Local\\Temp\\tmpfsmg6eww\\a.cpp(1): fatal error C1083: include ファイルを開けません。'cublas_v2.h':No such file or directory\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_00deaeca448d425da4d39ec650e4212a\\setup.py\", line 29, in <module>\n",
      "        ext_modules = cupy_setup_build.get_ext_modules()\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_00deaeca448d425da4d39ec650e4212a\\cupy_setup_build.py\", line 361, in get_ext_modules\n",
      "        extensions = make_extensions(arg_options, compiler, use_cython)\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_00deaeca448d425da4d39ec650e4212a\\cupy_setup_build.py\", line 255, in make_extensions\n",
      "        raise Exception('Your CUDA environment is invalid. '\n",
      "    Exception: Your CUDA environment is invalid. Please check above error log.\n",
      "    Options: {'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}\n",
      "    **************************************************\n",
      "    *** WARNING: nvcc path != CUDA_PATH\n",
      "    *** WARNING: nvcc path: C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\n",
      "    *** WARNING: CUDA_PATH: C:\\Users\\sinnd\\anaconda3\\Library\n",
      "    **************************************************\n",
      "    Include directories: ['C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\include', 'C:\\\\Program Files\\\\NVIDIA Corporation\\\\NvToolsExt\\\\include']\n",
      "    Library directories: ['C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\bin', 'C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\lib\\\\x64', 'C:\\\\Program Files\\\\NVIDIA Corporation\\\\NvToolsExt\\\\lib\\\\x64']\n",
      "    command 'C:\\\\Program Files\\\\Microsoft Visual Studio\\\\2022\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.32.31326\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit code 2\n",
      "    **************************************************\n",
      "    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'nvToolsExt.h']\n",
      "    *** WARNING: Skip installing cuda support\n",
      "    *** WARNING: Check your CFLAGS environment variable\n",
      "    **************************************************\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/4f/84/ff4c79b1b7120504909181f4b767be9c2542434ba1b8f2d126bace21c015/cupy-1.0.3.tar.gz#sha256=af177ea40073a2a9c0393e9614811885cc5e57ccb4c695e9cbf4d00691fd1799 (from https://pypi.org/simple/cupy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\sinnd\\anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\sinnd\\\\AppData\\\\Local\\\\Temp\\\\pip-install-vqangms_\\\\cupy_c72fbcad359f4acea2d0e68247d77fa9\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\sinnd\\\\AppData\\\\Local\\\\Temp\\\\pip-install-vqangms_\\\\cupy_c72fbcad359f4acea2d0e68247d77fa9\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-pip-egg-info-mf3bo1xp'\n",
      "         cwd: C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_c72fbcad359f4acea2d0e68247d77fa9\\\n",
      "    Complete output (27 lines):\n",
      "    C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_c72fbcad359f4acea2d0e68247d77fa9\\install\\build.py:38: SyntaxWarning: \"is not\" with a literal. Did you mean \"!=\"?\n",
      "      if _cuda_path is not 'NOT_INITIALIZED':\n",
      "    a.cpp\n",
      "    C:\\Users\\sinnd\\AppData\\Local\\Temp\\tmp5x7e5xqq\\a.cpp(1): fatal error C1083: include ファイルを開けません。'cublas_v2.h':No such file or directory\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_c72fbcad359f4acea2d0e68247d77fa9\\setup.py\", line 29, in <module>\n",
      "        ext_modules = cupy_setup_build.get_ext_modules()\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_c72fbcad359f4acea2d0e68247d77fa9\\cupy_setup_build.py\", line 361, in get_ext_modules\n",
      "        extensions = make_extensions(arg_options, compiler, use_cython)\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_c72fbcad359f4acea2d0e68247d77fa9\\cupy_setup_build.py\", line 255, in make_extensions\n",
      "        raise Exception('Your CUDA environment is invalid. '\n",
      "    Exception: Your CUDA environment is invalid. Please check above error log.\n",
      "    Options: {'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}\n",
      "    **************************************************\n",
      "    *** WARNING: nvcc path != CUDA_PATH\n",
      "    *** WARNING: nvcc path: C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\n",
      "    *** WARNING: CUDA_PATH: C:\\Users\\sinnd\\anaconda3\\Library\n",
      "    **************************************************\n",
      "    Include directories: ['C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\include', 'C:\\\\Program Files\\\\NVIDIA Corporation\\\\NvToolsExt\\\\include']\n",
      "    Library directories: ['C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\bin', 'C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\lib\\\\x64', 'C:\\\\Program Files\\\\NVIDIA Corporation\\\\NvToolsExt\\\\lib\\\\x64']\n",
      "    command 'C:\\\\Program Files\\\\Microsoft Visual Studio\\\\2022\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.32.31326\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit code 2\n",
      "    **************************************************\n",
      "    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'nvToolsExt.h']\n",
      "    *** WARNING: Skip installing cuda support\n",
      "    *** WARNING: Check your CFLAGS environment variable\n",
      "    **************************************************\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/d4/0f/79b84c548e0898ff39fa8a27f2a5134a5328b4f94e96bfc09fe60f63a167/cupy-1.0.2.tar.gz#sha256=5061fece3d64eb5759519cefd5b78d4c5ac5a324d33516c24c73114a7baf0551 (from https://pypi.org/simple/cupy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\sinnd\\anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\sinnd\\\\AppData\\\\Local\\\\Temp\\\\pip-install-vqangms_\\\\cupy_d703f53b729e4c2883060636bbc785cd\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\sinnd\\\\AppData\\\\Local\\\\Temp\\\\pip-install-vqangms_\\\\cupy_d703f53b729e4c2883060636bbc785cd\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-pip-egg-info-5clt45h8'\n",
      "         cwd: C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_d703f53b729e4c2883060636bbc785cd\\\n",
      "    Complete output (27 lines):\n",
      "    C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_d703f53b729e4c2883060636bbc785cd\\install\\build.py:38: SyntaxWarning: \"is not\" with a literal. Did you mean \"!=\"?\n",
      "      if _cuda_path is not 'NOT_INITIALIZED':\n",
      "    a.cpp\n",
      "    C:\\Users\\sinnd\\AppData\\Local\\Temp\\tmpdofexrt3\\a.cpp(1): fatal error C1083: include ファイルを開けません。'cublas_v2.h':No such file or directory\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_d703f53b729e4c2883060636bbc785cd\\setup.py\", line 29, in <module>\n",
      "        ext_modules = cupy_setup_build.get_ext_modules()\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_d703f53b729e4c2883060636bbc785cd\\cupy_setup_build.py\", line 359, in get_ext_modules\n",
      "        extensions = make_extensions(arg_options, compiler, use_cython)\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_d703f53b729e4c2883060636bbc785cd\\cupy_setup_build.py\", line 255, in make_extensions\n",
      "        raise Exception('Your CUDA environment is invalid. '\n",
      "    Exception: Your CUDA environment is invalid. Please check above error log.\n",
      "    Options: {'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}\n",
      "    **************************************************\n",
      "    *** WARNING: nvcc path != CUDA_PATH\n",
      "    *** WARNING: nvcc path: C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\n",
      "    *** WARNING: CUDA_PATH: C:\\Users\\sinnd\\anaconda3\\Library\n",
      "    **************************************************\n",
      "    Include directories: ['C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\include', 'C:\\\\Program Files\\\\NVIDIA Corporation\\\\NvToolsExt\\\\include']\n",
      "    Library directories: ['C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\bin', 'C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\lib\\\\x64', 'C:\\\\Program Files\\\\NVIDIA Corporation\\\\NvToolsExt\\\\lib\\\\x64']\n",
      "    command 'C:\\\\Program Files\\\\Microsoft Visual Studio\\\\2022\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.32.31326\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit code 2\n",
      "    **************************************************\n",
      "    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'nvToolsExt.h']\n",
      "    *** WARNING: Skip installing cuda support\n",
      "    *** WARNING: Check your CFLAGS environment variable\n",
      "    **************************************************\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/32/09/31c3c37ac0393293bcfd5404fd12512e16961cbeb48939c50fa1f395fb47/cupy-1.0.1.tar.gz#sha256=f189657a3873cc7ffba4c67632a1a41d53fa3276ce72344098991a773c0c5e05 (from https://pypi.org/simple/cupy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\sinnd\\anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\sinnd\\\\AppData\\\\Local\\\\Temp\\\\pip-install-vqangms_\\\\cupy_782bdc5961b4472f8f6c9a2d8dcf3441\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\sinnd\\\\AppData\\\\Local\\\\Temp\\\\pip-install-vqangms_\\\\cupy_782bdc5961b4472f8f6c9a2d8dcf3441\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-pip-egg-info-y4994hq8'\n",
      "         cwd: C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_782bdc5961b4472f8f6c9a2d8dcf3441\\\n",
      "    Complete output (25 lines):\n",
      "    a.cpp\n",
      "    C:\\Users\\sinnd\\AppData\\Local\\Temp\\tmpp8qt7svg\\a.cpp(1): fatal error C1083: include ファイルを開けません。'cublas_v2.h':No such file or directory\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_782bdc5961b4472f8f6c9a2d8dcf3441\\setup.py\", line 29, in <module>\n",
      "        ext_modules = cupy_setup_build.get_ext_modules()\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_782bdc5961b4472f8f6c9a2d8dcf3441\\cupy_setup_build.py\", line 351, in get_ext_modules\n",
      "        extensions = make_extensions(arg_options, compiler, use_cython)\n",
      "      File \"C:\\Users\\sinnd\\AppData\\Local\\Temp\\pip-install-vqangms_\\cupy_782bdc5961b4472f8f6c9a2d8dcf3441\\cupy_setup_build.py\", line 255, in make_extensions\n",
      "        raise Exception('Your CUDA environment is invalid. '\n",
      "    Exception: Your CUDA environment is invalid. Please check above error log.\n",
      "    Options: {'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}\n",
      "    **************************************************\n",
      "    *** WARNING: nvcc path != CUDA_PATH\n",
      "    *** WARNING: nvcc path: C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\n",
      "    *** WARNING: CUDA_PATH: C:\\Users\\sinnd\\anaconda3\\Library\n",
      "    **************************************************\n",
      "    Include directories: ['C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\include', 'C:\\\\Program Files\\\\NVIDIA Corporation\\\\NvToolsExt\\\\include']\n",
      "    Library directories: ['C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\bin', 'C:\\\\Users\\\\sinnd\\\\anaconda3\\\\Library\\\\lib\\\\x64', 'C:\\\\Program Files\\\\NVIDIA Corporation\\\\NvToolsExt\\\\lib\\\\x64']\n",
      "    command 'C:\\\\Program Files\\\\Microsoft Visual Studio\\\\2022\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.32.31326\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit code 2\n",
      "    **************************************************\n",
      "    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'nvToolsExt.h']\n",
      "    *** WARNING: Skip installing cuda support\n",
      "    *** WARNING: Check your CFLAGS environment variable\n",
      "    **************************************************\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/3d/42/662cab10a52b6dfe77cdae53fe533ccd16f01d5d4113a3b0b958b496443f/cupy-1.0.0.1.tar.gz#sha256=ba2dc6d74fa1307d09760facd7ee2cadada889e1ade519b75fd0d99b53fbbf59 (from https://pypi.org/simple/cupy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "ERROR: Could not find a version that satisfies the requirement cupy<1.1 (from chainer) (from versions: 1.0.0a1, 1.0.0b1, 1.0.0.1, 1.0.1, 1.0.2, 1.0.3, 2.0.0a1, 2.0.0b1, 2.0.0rc1, 2.0.0, 2.1.0, 2.1.0.1, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 3.0.0a1, 4.0.0b1, 4.0.0b2, 4.0.0b3, 4.0.0b4, 4.0.0rc1, 4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.4.0, 4.4.1, 4.5.0, 5.0.0a1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.3.0, 5.4.0, 6.0.0a1, 6.0.0b1, 6.0.0b2, 6.0.0b3, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0a1, 7.0.0b1, 7.0.0b2, 7.0.0b3, 7.0.0b4, 7.0.0rc1, 7.0.0, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.0, 7.8.0, 7.8.0.post1, 8.0.0a1, 8.0.0b1, 8.0.0b2, 8.0.0b3, 8.0.0b4, 8.0.0b5, 8.0.0rc1, 8.0.0, 8.1.0, 8.2.0, 8.3.0, 8.4.0, 8.5.0, 8.6.0, 9.0.0a1, 9.0.0a2, 9.0.0b1, 9.0.0b2, 9.0.0b3, 9.0.0rc1, 9.0.0, 9.1.0, 9.2.0, 9.3.0, 9.4.0, 9.5.0, 9.6.0, 10.0.0a1, 10.0.0a2, 10.0.0b1, 10.0.0b2, 10.0.0b3, 10.0.0rc1, 10.0.0, 10.1.0, 10.2.0, 10.3.0, 10.3.1, 10.4.0, 10.5.0, 10.6.0, 11.0.0a1, 11.0.0a2, 11.0.0b1, 11.0.0b2, 11.0.0b3, 11.0.0rc1, 11.0.0, 11.1.0, 11.2.0, 11.3.0, 11.4.0, 11.5.0, 11.6.0, 12.0.0a1, 12.0.0a2, 12.0.0b1, 12.0.0b2, 12.0.0b3, 12.0.0rc1)\n",
      "ERROR: No matching distribution found for cupy<1.1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: chainerrl in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (0.8.0)\n",
      "Requirement already satisfied: numpy>=1.10.4 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainerrl) (1.20.3)\n",
      "Requirement already satisfied: cached-property in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainerrl) (1.5.2)\n",
      "Requirement already satisfied: chainer>=2.0.0 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainerrl) (7.8.1)\n",
      "Requirement already satisfied: scipy in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainerrl) (1.7.1)\n",
      "Requirement already satisfied: pillow in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainerrl) (8.4.0)\n",
      "Requirement already satisfied: gym>=0.9.7 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainerrl) (0.23.0)\n",
      "Requirement already satisfied: six>=1.9.0 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer>=2.0.0->chainerrl) (1.16.0)\n",
      "Requirement already satisfied: typing-extensions in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer>=2.0.0->chainerrl) (4.5.0)\n",
      "Requirement already satisfied: protobuf>=3.0.0 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer>=2.0.0->chainerrl) (3.19.6)\n",
      "Requirement already satisfied: setuptools in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer>=2.0.0->chainerrl) (58.0.4)\n",
      "Requirement already satisfied: filelock in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from chainer>=2.0.0->chainerrl) (3.3.1)\n",
      "Requirement already satisfied: gym-notices>=0.0.4 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from gym>=0.9.7->chainerrl) (0.0.8)\n",
      "Requirement already satisfied: cloudpickle>=1.2.0 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from gym>=0.9.7->chainerrl) (2.0.0)\n",
      "Requirement already satisfied: importlib-metadata>=4.10.0 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from gym>=0.9.7->chainerrl) (6.0.0)\n",
      "Requirement already satisfied: zipp>=0.5 in c:\\users\\sinnd\\anaconda3\\lib\\site-packages (from importlib-metadata>=4.10.0->gym>=0.9.7->chainerrl) (3.6.0)\n"
     ]
    }
   ],
   "source": [
    "!cd ~\n",
    "!pip install chainer==2.1.0\n",
    "!pip install chainerrl"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f26b9a9a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
